[package]
name = "mars_calc"
version = "0.1.0"
authors = ["Len <len.choi@cyworldlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
